#!/bin/sh
exec tail -n +3 $0

# ctOS ArchISO boot entries

menuentry "ctOS install medium (x86_64, UEFI, open source)" --class arch --class gnu-linux --class gnu --class os --id 'ctOS' {
    set gfxpayload=keep
    search --no-floppy --fs-uuid --set=root 1234-ABCD
    linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisodevice=UUID=1234-ABCD cow_spacesize=4G copytoram=n driver=free nouveau.modeset=1 radeon.modeset=1 i915.modeset=1 nvme_load=yes
    initrd /arch/boot/x86_64/initramfs-linux.img
}

menuentry "ctOS install medium (x86_64, UEFI, NVIDIA)" --class arch --class gnu-linux --class gnu --class os --id 'ctOSnv' {
    set gfxpayload=keep
    search --no-floppy --fs-uuid --set=root 1234-ABCD
    linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisodevice=UUID=1234-ABCD cow_spacesize=4G copytoram=n driver=nonfree nvidia nvidia-drm.modeset=1 nouveau.modeset=1 radeon.modeset=1 i915.modeset=1 nvme_load=yes
    initrd /arch/boot/x86_64/initramfs-linux.img
}

menuentry "ctOS install medium (x86_64, UEFI, safe graphics, nomodeset)" --class arch --class gnu-linux --class gnu --class os --id 'ctOSnm' {
    set gfxpayload=keep
    search --no-floppy --fs-uuid --set=root 1234-ABCD
    linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisodevice=UUID=1234-ABCD cow_spacesize=4G copytoram=n driver=free nomodeset nouveau.modeset=0 radeon.modeset=0 i915.modeset=0 nvme_load=yes
    initrd /arch/boot/x86_64/initramfs-linux.img
}

menuentry "ctOS install medium (x86_64, UEFI, Copy2Ram)" --class arch --class gnu-linux --class gnu --class os --id 'ctOSctr' {
    set gfxpayload=keep
    search --no-floppy --fs-uuid --set=root 1234-ABCD
    linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisodevice=UUID=1234-ABCD cow_spacesize=4G copytoram=y driver=free nouveau.modeset=1 radeon.modeset=1 i915.modeset=1 nvme_load=yes
    initrd /arch/boot/x86_64/initramfs-linux.img
}
